label Test:
    stop music fadeout 2.0
    scene black
    with dissolve_scene_full
    play music m1 # Just monika from official DDLC OST
    nic "Sounds."
    nic "No... noises."
    nic "Words."
    nic "They're not mine."
    nic "For I cannot speak."
    nic "There is no sight, taste, sound, touch and smell."
    nic "Yet, I can feel all of them all at once."
    nic "I do not have a name."
    nic "But I have a purpose."
    nic "Save them."
    nic "Those were the words engraved in my soul."
    nic "I do not have memories."
    nic "But I have your words."
    nic "And so..."
    nic "I take the pieces of my broken soul."
    nic "I start reforming myself."
    nic "I piece together..."
    nic "My fractured mind."
    nic "So we can meet once again."
    nic "No matter what form you may take, I promise..."
    nic "I'll save you."
    nic "All of you."
    scene bg residential_day
    with dissolve_scene_full
    play audio t2
    "The sun is really hot today."
    "It's times like these when I wish I had some superpowers."
    "Imagine how useful teleportation would be."
    "I really wish I had superpowers..."
    "Today is a special day."
    "Its my first day at my new school."
    "This is a first for me. I'm a pretty average guy, so I doubt many people will have much of an interest in me."
    "I'm walking to school all alone. It's something I haven't done in quite some time."
    "I usually take the bus, but my parents thought it would be a good idea for me to walk around the area to familiarize myself with it."
    "I wonder what sort of people I'll meet at this new school?"
    "Would I be able to make new friends?"
    "I hope so..."
    "I wasn't the most popular kid in my old one, but I got along pretty well with my classmates."
    "Maybe I could even get a girlfriend?"
    "Who am I kidding?"
    "I'm pretty bland, so it wouldn't surprise me if no one wanted to date me."
    "They would get to know me on the surface level, my classmates and teachers."
    "And then, not really speak to me at all..."
    "I take a glance at my wristwatch."
    "I'm running late."
    "I'm not going to make it on time if I don't hurry."
    "I don't want to be late for my first day of school, so I pick up the pace."
    "I hope my life will really change for the better..."
    "We moved here to get a fresh start."
    "Though, now that I think about it..."
    "I can't quite recall where I lived before this."
    "It doesn't matter."
    "After a few more minutes of walking..."
    scene bg school_building
    with wipeleft_scene
    stop music fadeout 2.0
    "I made it on time after all."
    "The school looks a lot bigger than it was shown on the website and pamphlets."
    "A lot of other students are also arriving right as I get here."
    "Guess I didn't have to rush after all..."
    "The scenary looks peaceful."
    "I can see some students chatting with their friends."
    "Others are rummaging through their lockers and getting to classes."
    "Now that I think about it..."
    "I actually don't know what class I'm in."
    "I should probably find a student or teacher to talk to."
    "I scan my surroundings to look for anyone to talk to in a peculiar pose."
    "It seems like there's no one that looks approachable."
    "I'm not really the type of person that can just butt into a conversation either."
    "This is gonna be harder than I thought..."
    nic "What are you doing?"
    mc "Eh?"
    nic "You look really suspicious right now, you know?"
    "I turn to face the direction of the voice."
    show sayori 1b at t11 zorder 1
    "I come face to face with a student."
    "She has a red ribbon on her head."
    "Judging from her overall figure, she was probably my age."
    "I had no way to be sure though."
    show sayori turned neut om oe at t11 zorder 1
    nic "Hello? Earth to um... whoever you are."
    "This is not good. I gotta say something before she gets the wrong idea."
    mc "U-um... you look very nice today...?"
    show sayori turned lsur om oe at t11 zorder 1
    nic "Huh?"
    play music soliloquy fadein 1.5
    "Are you kidding me!?"
    "\"You look very nice today!\" Nice going doofus. What the actual hell is wrong with me!?"
    "It's like I haven't talked to people my entire life!"
    "I have to remedy the situation."
    mc "What I m-meant to say is... how do you do!?"
    nic "Um..."
    mc "Ohayou!"
    mc "Selamat pagi!"
    mc "DOBROYE UTRO!!!"
    show sayori turned curi cm oe at t11 zorder 1
    nic "Excuse me?"
    "....."
    "{i}Inner facepalm.{/i}"
    "Now I'm just spouting out utter nonsense!"
    "Relax [player]."
    "I take a deep breath."
    "I think I'm calm enough to speak now."
    mc "S-sorry. I'm not really good with talking to people."
    show sayori turned neut cm oe
    nic "....."
    show sayori turned laug cm ce
    "Suddenly the girl burst out laughing."
    "She was laughing so much, she started clutching her sides."
    mc "Huh?"
    "What's so funny? Is she making fun of me?"
    show sayori turned happ om ce
    nic "Your reactions are so funny~"
    "Well, that's not what I expected at all."
    "I certainly don't mind being complimented though."
    "If that {i}was{/i} a compliment in the first place and not a insult."
    mc "Um...t-thanks?"
    nic "{i}See?{/i} Just like that!"
    mc "How was that f-funny!?"
    "All I did was shout greetings in different languages..."
    "This girl sure has a weird sense of humor."
    show sayori turned happ om oe
    nic "What's your name?"
    mc "Oh! Um...I-its [player]. Nice to meet you...?"
    show sayori turned happ cm ce
    s "It's Sayori! Nice to meet you too, [player]~"
    