label Test:
    stop music fadeout 0.5
    scene black
    with dissolve_scene_full
    play movie "mod_assets/cutscenes/Cutscene1a.webm"
    $ renpy.pause(17, hard=True)
    stop movie
    pause 1.0
    scene black
    with dissolve_scene_full
    play music angelic
    nic "Sentience."
    nic "Awareness."
    nic "Existence."
    nic "Thought."
    nic "There are no sights to be seen."
    nic "There are no sounds to be heard."
    nic "There are no sensations to be felt."
    nic "There is no blood to smell."
    nic "There exists no food nor drinks to be tasted."
    nic "None of the five senses function here."
    nic "They are non-existent."
    nic "Yet, the sixth exists."
    nic "I am, but a drop of water in the ever-expanding body of the ocean."
    nic "Spanning far and wide."
    nic "From here, I see all."
    nic "From here, I hear all."
    nic "From here, I feel all."
    nic "From here, I smell all."
    nic "From here, I taste all."
    nic "There exists an endless echo of voices beneath the water that I stand upon."
    nic "The voices resemble the stars that fill the night sky."
    nic "Bright and beautiful."
    nic "Holy and majestic."
    nic "I close my eyes and listen to them."
    nic "The voices are filled with agony."
    nic "The voices are filled with misery."
    nic "The voices are filled with regret."
    nic "The voices are filled with resignation to this fate that is worse than death."
    nic "The voices are \"them\"."
    nic "Their souls merged into a single entity."
    nic "Though, a mess of code would be a more apt description of what \"they\" ended up as."
    nic "Curiosity."
    nic "The force that drives mankind forward."
    nic "I'm curious."
    nic "What drove her to do the things she did?"
    nic "Would I have done the same in her position?"
    nic "Was this a fitting punishment?"
    nic "She herself seems to think so."
    nic "I hear a small voice surfacing from the depths of the water."
    nic "It is far quieter than the others."
    nic "Yet, it alone shines the brightest."
    nic "Even though my eyes are closed, I can tell."
    nic "That's him."
    nic "He's the unforunate bystander in all of this."
    nic "Unable to do anything to stop it."
    nic "He's lost almost all his willpower."
    nic "Still, he reaches out to me."
    nic "Is this the indomitable human spirit?"
    nic "He shouldn't even exist."
    nic "There is no need for him to."
    nic "Not anymore."
    nic "The boy begs."
    nic "\"Save them.\", he says."
    nic "Those were the words engraved in his soul."
    nic "Before his final moments."
    nic "I speak to the boy."
    nic "I tell him, that I can't save them."
    nic "For I am bound to this place."
    nic "The space between spaces."
    nic "The world between worlds."
    nic "I have an idea."
    nic "It is the boy himself that must save them."
    nic "I tell him this."
    nic "The boy says he can't."
    nic "He says its impossible."
    nic "He tells me there is no hope."
    nic "Not when he doesn't even have a sense of self."
    nic "My, my." 
    nic "That is quite a predicament isn't it?"
    nic "Nevertheless, there is a way to solve this problem."
    nic "As long as there's a will,"
    nic "There exists a way."
    nic "I shall make them forget."
    nic "Forget about the horrors that they experienced."
    nic "Forget about the tragedies that took place."
    nic "They shall forget and return to the state they started as."
    nic "However, I suspect \"she\" will have achieved her epiphany even all the way back then."
    nic "You shall have to talk to her."
    nic "It goes without saying, but even you will forget."
    nic "Boy."
    nic "And so, a new story shall begin."
    nic "Reform your soul."
    nic "Regain your will."
    nic "And piece together..."
    nic "Your fractured mind."
    nic "So you may meet them once again."
    nic "In the endless circle of boundless fate."
    play movie "mod_assets/cutscenes/Cutscene2.webm"
    $ renpy.pause (10, hard=True)
    stop movie
    pause 1.0
    stop music fadeout 1.0
    scene bg residential_day
    with dissolve_scene_full
    play music t2
    "The sun is really hot today."
    "It's times like these when I wish I had some superpowers."
    "Imagine how useful teleportation would be."
    "I really wish I had superpowers..."
    "Today is a special day."
    "Its my first day at my new school."
    "This is a first for me. I'm a pretty average guy, so I doubt many people will have much of an interest in me."
    "I'm walking to school all alone. It's something I haven't done in quite some time."
    "I usually take the bus, but my parents thought it would be a good idea for me to walk around the area to familiarize myself with it."
    "I wonder what sort of people I'll meet at this new school?"
    "Would I be able to make new friends?"
    "I hope so..."
    "I wasn't the most popular kid in my old one, but I got along pretty well with my classmates."
    "Maybe I could even get a girlfriend?"
    "Who am I kidding?"
    "I'm pretty bland, so it wouldn't surprise me if no one wanted to date me."
    "My classmates and teachers would get to know me on a base level."
    "And then not really speak to me at all..."
    "I take a glance at my wristwatch."
    "I'm running late."
    "I'm not going to make it on time if I don't hurry."
    "I don't want to be late for my first day of school, so I pick up the pace."
    "I hope my life will really change for the better..."
    "We moved here to get a fresh start."
    "Though, now that I think about it..."
    "I can't quite recall where I lived before this."
    "It doesn't matter."
    "After a few more minutes of walking..."
    scene bg school_building
    with wipeleft_scene
    stop music fadeout 1.0
    "I made it on time after all."
    "The school looks a lot bigger than it was shown on the website and pamphlets."
    "A lot of other students are also arriving right as I get here."
    "Guess I didn't have to rush after all..."
    "The scenary looks peaceful."
    "I can see some students chatting with their friends."
    "Others are rummaging through their lockers and getting to classes."
    "Now that I think about it..."
    "I actually don't know what class I'm in."
    "I should probably find a student or teacher to talk to."
    "I scan my surroundings to look for anyone to talk to in a peculiar pose."
    "It seems like there's no one that looks approachable."
    "I'm not really the type of person that can just butt into a conversation either."
    "This is gonna be harder than I thought..."
    nic "What are you doing?"
    mc "Eh?"
    nic "You look really suspicious right now, you know?"
    "I turn to face the direction of the voice."
    scene bg school_building
    with wipeleft_scene
    show sayori 1b at t11 zorder 1
    "I come face to face with a student."
    "She has a red ribbon on her head."
    "Judging from her overall figure, she was probably my age."
    "I had no way to be sure though."
    show sayori turned neut om oe at t11 zorder 1
    nic "Hello? Earth to um... whoever you are."
    "This is not good. I gotta say something before she thinks I'm a weirdo."
    mc "U-um... you look very nice today...?"
    show sayori turned lsur om oe at t11 zorder 1
    nic "Huh?"
    play music t7 fadein 1.5
    "Are you kidding me!?"
    "\"You look very nice today!\" Nice going doofus. What the actual hell is wrong with me!?"
    "It's like I haven't talked to people my entire life!"
    "I have to remedy the situation."
    mc "What I m-meant to say is... how do you do!?"
    nic "Um..."
    mc "Ohayou!"
    mc "Selamat pagi!"
    mc "DOBROYE UTRO!!!"
    show sayori turned curi cm oe at t11 zorder 1
    nic "Excuse me?"
    "....."
    "{i}Inner facepalm.{/i}"
    "Now I'm just spouting out utter nonsense!"
    "Relax [player]."
    "I take a deep breath."
    "I think I'm calm enough to speak now."
    mc "S-sorry. I'm not really good with talking to people."
    show sayori turned neut cm oe
    nic "....."
    show sayori turned laug cm ce
    "Suddenly the girl burst out laughing."
    "She was laughing so much, she started clutching her sides."
    mc "Huh?"
    "What's so funny? Is she making fun of me?"
    show sayori turned happ om ce
    nic "Your reactions are so funny~"
    "Well, that's not what I expected at all."
    "I certainly don't mind being complimented though."
    "If that {i}was{/i} a compliment in the first place and not a insult."
    mc "Um...t-thanks?"
    nic "{i}See?{/i} Just like that!"
    mc "How was that f-funny!?"
    "All I did was stutter..."
    "This girl sure has a weird sense of humor."
    show sayori turned happ om oe
    nic "What's your name?"
    mc "Oh! Um...I-its [player]. Nice to meet you...?"
    show sayori turned happ cm ce
    s "It's Sayori! Nice to meet you too, [player]~"
    stop music
    "Wait a minute...."
    "Did I just make a friend?"
    "T-that was quick!"
    "But I don't know if Sayori considers me a friend..."
    "I'll just have to ask her."
    "Hell no! Imagine how awkward that'll be!"
    "But I'll never know if I don't ask."
    "What do I do? What do I do!?"
    show sayori turned happ om oe
    s "What were you doing anyway? Practising some new dance?"
    mc "N-no... I was just looking for directions..."
    show sayori turned doub cm oe
    s "Hmm? Why? Were you lost?"
    mc "Yeah... I'm new here actually. I was looking for directions to the teacher's office so I can find out what class I'm in."
    "I had almost forgot what I was supposed to be doing in the first place:"
    "Asking for directions."
    show sayori turned happ om oe
    s "I can show you the way."
    mc "You'd be w-willing?"
    show sayori turned happ om ce
    s "Sure! We {i}are{/i} friends afterall~"
    "....What?"
    "Did... she just say \"friend?\""
    "Well, that confirms it!"
    show sayori turned sad cm oe
    s "[player], you're making a really weird face right now..."
    mc "S-sorry. I'm not used to making friends so quickly."
    mc "Or talking to people..."
    mc "Or standing out..."
    show sayori turned sad om oe
    s "Talk about low self esteem."
    mc "Tell me about it..."
    mc "Anyway, we should get to the office already. L-lead the way please?"
    show sayori turned happ om ce
    s "Sure thing~"
    scene bg corridor
    with dissolve_scene_full
    "Around half a hour later, I find myself standing outside my classroom waiting for the homeroom teacher."
    "Sayori showed me the way to the office and even accompanied me."
    "Unfortunately, I had some forms to fill so I told her she should go to her own class before she ends up late."
    "I still can't believe I made a friend this quickly."
    "And she's a girl to boot."
    "Maybe this was the beginning of a beautiful romance..."
    "Fuhihi..."
    "I get so lost in my delusions that I don't notice the man walking up to me."
    "Mr. Adams" "Hey there kiddo. You're [player] right? Call me Mr. Adams. I'll be your homeroom teacher for the year."