label Test:
    stop music fadeout 0.5
    scene black
    with dissolve_scene_full
    play movie "mod_assets/cutscenes/Cutscene1a.webm"
    $ renpy.pause(17, hard=True)
    stop movie
    pause 1.0
    scene black
    with dissolve_scene_full
    play music angelic
    nic "Sentience."
    nic "Awareness."
    nic "Existence."
    nic "Thought."
    nic "There are no sights to be seen."
    nic "There are no sounds to be heard."
    nic "There are no sensations to be felt."
    nic "There is no blood to smell."
    nic "There exists no food nor drinks to be tasted."
    nic "None of the five senses function here."
    nic "They are non-existent."
    nic "Yet, the sixth exists."
    nic "I am, but a drop of water in the ever-expanding body of the ocean."
    nic "Spanning far and wide."
    nic "From here, I see all."
    nic "From here, I hear all."
    nic "From here, I feel all."
    nic "From here, I smell all."
    nic "From here, I taste all."
    nic "There exists an endless echo of voices beneath the water that I stand upon."
    nic "The voices resemble the stars that fill the night sky."
    nic "Bright and beautiful."
    nic "Holy and majestic."
    nic "I close my eyes and listen to them."
    nic "The voices are filled with agony."
    nic "The voices are filled with misery."
    nic "The voices are filled with regret."
    nic "The voices are filled with resignation to this fate that is worse than death."
    nic "The voices are \"them\"."
    nic "Their souls merged into a single entity."
    nic "Though, a mess of code would be a more apt description of what \"they\" ended up as."
    nic "Curiosity."
    nic "The force that drives mankind forward."
    nic "I'm curious."
    nic "What drove her to do the things she did?"
    nic "Would I have done the same in her position?"
    nic "Was this a fitting punishment?"
    nic "She herself seems to think so."
    nic "I hear a small voice surfacing from the depths of the water."
    nic "It is far quieter than the others."
    nic "Yet, it alone shines the brightest."
    nic "Even though my eyes are closed, I can tell."
    nic "That's him."
    nic "He's the unforunate bystander in all of this."
    nic "Unable to do anything to stop it."
    nic "He's lost almost all his willpower."
    nic "Still, he reaches out to me."
    nic "Is this the indomitable human spirit?"
    nic "He shouldn't even exist."
    nic "There is no need for him to."
    nic "Not anymore."
    nic "The boy begs."
    nic "\"Save them.\", he says."
    nic "Those were the words engraved in his soul."
    nic "Before his final moments."
    nic "I speak to the boy."
    nic "I tell him, that I can't save them."
    nic "For I am bound to this place."
    nic "The space between spaces."
    nic "The world between worlds."
    nic "I have an idea."
    nic "It is the boy himself that must save them."
    nic "I tell him this."
    nic "The boy says he can't."
    nic "He says its impossible."
    nic "He tells me there is no hope."
    nic "Not when he doesn't even have a sense of self."
    nic "My, my." 
    nic "That is quite a predicament isn't it?"
    nic "Nevertheless, there is a way to solve this problem."
    nic "As long as there's a will,"
    nic "There exists a way."
    nic "I shall make them forget."
    nic "Forget about the horrors that they experienced."
    nic "Forget about the tragedies that took place."
    nic "They shall forget and return to the state they started as."
    nic "However, I suspect \"she\" will have achieved her epiphany even all the way back then."
    nic "You shall have to talk to her."
    nic "It goes without saying, but even you will forget."
    nic "Boy."
    nic "And so, a new story shall begin."
    nic "Reform your soul."
    nic "Regain your will."
    nic "And piece together..."
    nic "Your fractured mind."
    nic "So you may meet them once again."
    nic "In the endless circle of boundless fate."
    window hide
    play movie "mod_assets/cutscenes/Cutscene2.webm"
    $ renpy.pause (10, hard=True)
    stop movie
    window auto
    stop music fadeout 2.0
    scene bg class_day
    with dissolve_scene_full
    "Let me ask you a question."
    "Let's say the universe started existing mere seconds ago."
    "That everything in your life was fabricated."
    "Would you be able to accept that truth?"
    "Can you bear the burden of that epiphany without losing your sanity?"
    "I bet a lot of people couldn't."
    "Some would even try to reject it."
    "I let out a sigh and checked the time."
    "Class was almost over."
    "I was bored out of my mind."
    "It was just my third week here at my new school, but I was already getting sick of the classes."
    "I don't particularly hate studying."
    "I"