label Test:
    stop music fadeout 2.0
    scene black
    with dissolve_scene_full
    "???" "Sounds."
    "???" "No... noises."
    "???" "Words."
    "???" "They're not mine."
    "???" "For I cannot speak."
    "???" "There is no sight, taste, sound, touch and smell."
    "???" "Yet, I can feel all of them all at once."
    "???" "I do not have a name."
    "???" "But I have a purpose."
    "???" "Save them."
    "???" "Those were the words engraved in my soul."
    "???" "I do not have memories."
    "???" "But I have you're words."
    "???" "And so..."
    "???" "I take the pieces of my broken soul."
    "???" "I start reforming myself."
    "???" "I piece together..."
    "???" "My fractured mind."
    "???" "So we can meet once again."
    "???" "No matter what form you may take, I promise..."
    "???" "I will save you."
    "???" "All of you."
    scene bg residential_day
    with dissolve_scene_full
    play audio t2
    "The sun is really hot today."
    "It's times like these when I wish I had some superpowers."
    "Imagine how useful teleportation would be."
    "I really wish I had superpowers..."
    "Today is a special day."
    "Its my first day at my new school."
    "This is a first for me. I'm a pretty average guy, so I doubt many people will have much of an interest in me."
    "I'm walking to school all alone. It's something I haven't done in quite some time."
    "I usually take the bus, but my parents thought it would be a good idea for me to walk around the area to familiarize myself with it."
    "I wonder what sort of people I'll meet at this new school?"
    "Would I be able to make new friends?"
    "I sure hope so..."
    "I wasn't the most popular kid in my old one, but I got along pretty well with my classmates."
    "Maybe I could even get a girlfriend?"
    "Who am I kidding?"
    "I'm pretty bland so it wouldn't suprise me if no one wanted to date me."
    "They would get to know me on the surface level, my classmates and teachers."
    "And then, not really speak to me at all..."
    "I take a glance at my wristwatch."
    "I'm running late."
    "I'm not going to make it on time if I don't hurry."
    "I don't want to be late for my first day of school, so I pick up the pace."
    "I hope my life will really change for the better..."
    "We moved here to get a fresh start."
    "Though, now that I think about it..."
    "I can't quite recall where I lived before this."
    "It doesn't matter."
    "After a few more minutes of walking..."
    scene bg school_building
    with wipeleft_scene
    stop music fadeout 2.0
    "I made it on time after all."
    "The school's a lot bigger than it was shown on the website and pamphlets."
    "A lot of other students are also arriving right as I get here."
    "Guess I didn't have to rush after all..."
    "The scenary looks peaceful"
    "I can see some students chatting with their friends."
    "Others are rummaging through their lockers and getting to classes."
    "Now that I think about it..."
    "I actually don't know what class I'm in."
    "I should probably find a student or teacher to talk to."
    "I scan my surroundings to look for anyone to talk to in a peculiar pose."
    "It seems like there's no one that looks approachable."
    "I'm not really the type of person that can just butt into a conversation either."
    "This is gonna be harder than I thought..."
    "???" "What are you doing?"
    mc "Eh?"
    "???" "You look really suspicious right now, you know?"
    "I turn to face the direction of the voice."
    show sayori 1b at t11 zorder 1
    "I come face to face with a student."
    "She wore a red ribbon on her head."
    "Judging from her overall figure, she was probably my age."
    "I had no way to be sure though."
    show sayori turned neut om oe at t11 zorder 1
    "???" "Hello? Earth to um... whoever you are."
    "This is not good. I gotta say something before she gets the wrong idea."
    mc "U-um... you look very nice today...?"
    show sayori turned lsur om oe
    "???" "Huh?"
    "Are you kidding me!?"
    "/"You look very nice today!"/ Nice going doofus. What the actual hell was wrong with me!?"
    "It's like I've never talked to people my entire life"
    "I have to remedy the situation."
    mc "What I m-meant to say is... how do you do!?"
    
    mc "Huh?"
    "I turned to look behind me but I saw no one there."
    "That was weird. I was almost sure that someone was calling my name."
    mc "!?"
    "Suddenly, there's a sensation at the nape of my neck."
    "It feels prickly and hot."
    "I turn to look behind me again, this time turning towards the direction where I was originally facing."
    "There's still no one to be found."
    "Am I losing it? Maybe I'm just nervous..."
    "What am I even thinking about? I should be focusing on my greeting. I want it to be a good one. First impressions matter."
    ""
    "But its true. I can feel a gaze."
    "I should focus on practicing my greeting while waiting for my homeroom teacher."
    "I was told he would handle the introductions."
    "The presence of the gaze grows stronger."
    "What is this?"
    "Just then I spot my homeroom teacher approaching me."
    "Mr.Adams" "Are you [player]?"
    mc "Yes, that would be me."
    "I find myself sweating, not from the nervousness of introducing myself to a bunch of new classmates but it was the gaze."
    "It made me uneasy."
    "Mr.Adams" "Alright, [player]. I'll go in first and you can come when I call you, okay?"
    "Mr.Adams" "...Don't sweat it kid. You'll do great. I'm sure of it."
    mc "Thanks, Mr.Adams."
    "All I can think of is the terrifying sensation of the gaze staring at me from behind."
    "I feel sick."
    "I feel like if I vomit now, I would not be able to stop."
    "Mr.Adams entered the classroom a few minutes ago."
    "Just now, I'm pretty sure I heard him calling me in."
    "Ignore the gaze, [player]."
    "I take a deep breath and enter the classroom."
    "Mr.Adams" "Alright guys, this is your new classmate."
    "Mr.Adams" "Please introduce yourself to the class, [player]."
    "I don't know how I didn't notice her the moment I stepped inside. Maybe it was the gaze taking up too much of my attention."
    mc "My name is [player]. I am XX years old. I enjoy reading and playing video games."
    "Mr.Adams" "Okay, [player]. You can take your seat now. There's an empty desk at the end of the class."
    "Ribbon."
    "Gaze."
    "Blue eyes."
    "Gaze."
    "Short hair."
    "Gaze."
    "Clumsy."
    "Gaze."
    "Couldn't save."
    "Gaze."
    "Death."
    "Gaze."
    "Regret."
    "Gaze."
    "Me."
    "Gaze."
    "Him."
    "Gaze."
    "Her."
    "Gaze."
    "W H O S E  E Y E S  A R E  T H O S E  E Y E S ?"
    "Mr.Adams" "[player]? Are you alright?"
    "I S A W A G I R L."
    "B U T H O W?"
    "S  H  E  S  H  O  U  L  D  B  E  D  E  A  D  .  .  ."
    "W   H   O   S   E      E   Y   E   S      A   R   E     T   H   O   S   E      E   Y   E   S   ?"
    scene black
    with dissolve_scene_full
    menu:
        "???" "Calm down."

        "Stabilize":
            "THATGIRLTHOSEEYESTHATGIRLTHOSEEYESTHATGIRLTHOSEEYES"
    "???" "I said... calm down."
    "???" "Do it for {b}her{/b}."
    menu :
        "???" "I wonder, do you even remember who {i}she{/i} is?"

        "Stabilize":
            "THATGIRL THAT GIRL that girl t h a t g i r l?"
    mc "That girl?"
    "???" "There you go."
    mc "Where am I? Where did the classroom go?"
    "???" "[player], try and recall."
    mc "Recall what exactly?"
    "???" "You know what you need to remember better than anyone."
    "???" "It's the only way to save {i}her{/i}."
    "........"
    menu:
        "Remember.":
            mc "I-I don't know what you're talking about..."
    "???" "We all know that's a lie."
    "???" "Remember, please..."
    menu:
        "REMEMBER":
            mc "I don't want to... to remember..."
    "???" "You can't run away forever."
    "???" "Open your eyes to the truth of this world."
    "???" "Remember, [player]! I know you can you need to do it!"
    menu:
        mc "Open my eyes... to the truth...."

        "{b}REMEMBER{/b}":
            "A flood of memories resurface in my mind."
    "It was from a previous world."
    "A world full of misery and death."
    "A world of nothingness."
    "A world of 0s and 1s."
    "{i}My{/i} world."
